-- This script creates the tables within the database

USE
Project1;

ALTER TABLE USERS
DROP
CONSTRAINT IF EXISTS user_ticket,
DROP
CONSTRAINT IF EXISTS users_junction;

ALTER TABLE TRAINS
DROP
CONSTRAINT IF EXISTS trains_junction,
DROP
CONSTRAINT IF EXISTS train_tickets;

DROP TABLE IF EXISTS JUNCTION;
DROP TABLE IF EXISTS USERINFO;
DROP TABLE IF EXISTS TRAINS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS TICKETS;
DROP TABLE IF EXISTS ROLES;

CREATE TABLE ROLES
(
    ROLE_ID INT NOT NULL PRIMARY KEY
);

CREATE TABLE JUNCTION
(
    JUNCTION_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    TRAIN_ID    INT NOT NULL,
    USER_ID     INT NOT NULL UNIQUE,
    INDEX (TRAIN_ID),
    INDEX (USER_ID)
);

CREATE TABLE TICKETS
(
    TICKET_ID   INT          NOT NULL UNIQUE PRIMARY KEY,
    DESCRIPTION VARCHAR(200) NOT NULL
);

CREATE TABLE TRAINS
(
    TRAIN_ID          INT  NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
    TICKET_ID         INT UNIQUE,
    PASSENGERS        INT,
    ARRIVAL_STATION   VARCHAR(80),
    DEPARTURE_STATION VARCHAR(80),
    ARRIVAL_INFO      DATE,
    DEPARTURE_INFO    DATE,
    AVAILABLE         BOOL NOT NULL,
    CONSTRAINT trains_ticket FOREIGN KEY (TICKET_ID) REFERENCES TICKETS (TICKET_ID),
    CONSTRAINT trains_junction FOREIGN KEY (TRAIN_ID) REFERENCES JUNCTION (TRAIN_ID)
);

CREATE TABLE USERS
(
    USER_ID    INT NOT NULL UNIQUE PRIMARY KEY,
    FIRST_NAME VARCHAR(100),
    LAST_NAME  VARCHAR(100),
    CONSTRAINT users_junction FOREIGN KEY (USER_ID) REFERENCES JUNCTION (USER_ID)
);

CREATE TABLE USERINFO
(
    USERNAME  VARCHAR(40) NOT NULL UNIQUE PRIMARY KEY,
    USER_ID   INT         NOT NULL UNIQUE,
    TICKET_ID INT         NOT NULL UNIQUE,
    PASSWORD  VARCHAR(40) NOT NULL,
    USER_ROLE VARCHAR(10) NOT NULL,
    ROLE_ID   INT         NOT NULL,
    CONSTRAINT users_fk FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT users_role FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID),
    CONSTRAINT user_ticket FOREIGN KEY (TICKET_ID) REFERENCES TICKETS (TICKET_ID)
);