-- This script populates the database with dummy data

USE
Project1;


INSERT INTO ROLES
VALUES (0);
INSERT INTO ROLES
VALUES (1);

-- INSERT INTO JUNCTION
INSERT INTO JUNCTION
VALUES (1, 1);
INSERT INTO JUNCTION
VALUES (2, 2);

INSERT INTO JUNCTION (train, `user`)
VALUES (NULL, NULL);
INSERT INTO USERS (FIRST_NAME, LAST_NAME)
VALUES ('Kollier', 'Martin');

-- INSERT INTO TICKETS
INSERT INTO TICKETS (TICKET_ID, DESCRIPTION)
VALUES (1, "My Description");
INSERT INTO TICKETS (TICKET_ID, DESCRIPTION)
VALUES (2, "I'm with stupid");

-- INSERT INTO TRAINS
INSERT INTO TRAINS (TRAIN_ID, TICKET_ID, PASSENGERS, ARRIVAL_STATION, DEPARTURE_STATION, ARRIVAL_INFO, DEPARTURE_INFO,
                    AVAILABLE)
VALUES (1, 1, 2, "LA", "GA", '2021-12-31 12:23:10', '2022-01-04 04:00:30', true);
INSERT INTO TRAINS (TRAIN_ID, TICKET_ID, PASSENGERS, ARRIVAL_STATION, DEPARTURE_STATION, ARRIVAL_INFO, DEPARTURE_INFO,
                    AVAILABLE)
VALUES (2, 2, 2, "LA", "GA", '2021-12-31 12:23:10', '2022-01-04 04:00:30', true);

-- INSERT INTO USERS
INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME)
VALUES (1, 'Erika', 'Johnson');
INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME)
VALUES (2, 'Kollier', 'Martin');

-- INSERT INTO USERINFO 
INSERT INTO USERINFO
VALUES ('EJohnson', 1, 1, 'password', 'Passenger', 0);
INSERT INTO USERINFO
VALUES ('KMartin', 2, 2, 'password', 'Admin', 1);